server:
  port: 8080
  servlet:
    context-path: /api
logging: 
  level: 
    root: info
spring:
  datasource:
    url: jdbc:postgresql://34.72.212.70:5432/cbustos-db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: postgres
    password: GoLbFBfCfLfsnqqK
management:
  endpoint:
    health:
      probes:
        enabled: true